/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Utakmica;
import static forme.JPanelKreirajTiket.vratiDatumKraj;
import static forme.JPanelKreirajTiket.vratiDatumSaNulom;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import komponente.tabela.model.ModelTabeleUtakmice;
import komunikacija.KontrolerKI;
import pdf.Pdf;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author KORISNIK
 */
public class JDialogLista extends javax.swing.JDialog {

    /**
     * Creates new form JDialogLista
     */
    public JDialogLista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooserPrviDatum = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserDrugiDatum = new com.toedter.calendar.JDateChooser();
        jButtonGnerisiListu = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Generisi listu utakmica od:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("do:");

        jButtonGnerisiListu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGnerisiListu.setText("Generisi listu");
        jButtonGnerisiListu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGnerisiListuActionPerformed(evt);
            }
        });

        jButtonOtkazi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Prikazi listu");
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButtonGnerisiListu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserPrviDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserDrugiDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jButtonOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDrugiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooserPrviDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGnerisiListu)
                    .addComponent(jButtonOtkazi))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonGnerisiListuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGnerisiListuActionPerformed
        // TODO add your handling code here:
        try {

            if (jDateChooserPrviDatum.getDate() == null || jDateChooserDrugiDatum.getDate() == null) {
                throw new Exception("Morate uneti oba datuma!");

            }

            HashMap<String, Date> hmap = new HashMap<>();
            hmap.put("prviDatum", (vratiDatumSaNulom(jDateChooserPrviDatum.getDate())));
            hmap.put("drugiDatum", (vratiDatumKraj(jDateChooserDrugiDatum.getDate())));

            KlijentTransferObjekat zahtev12 = new KlijentTransferObjekat();
            zahtev12.setOperacija(KlijentTransferObjekat.VRATI_UTAKMICE);
            zahtev12.setObjekatOperacije(hmap);
            KontrolerKI.vratiInstancu().posaljiZahtev(zahtev12);
            ServerTransferObjekat odgovor12 = KontrolerKI.vratiInstancu().procitajOdgovor();
            if (odgovor12.getSignal() == -1) {
                throw new Exception(odgovor12.getPoruka());
            }
            List<Utakmica> utakmicee = (List<Utakmica>) odgovor12.getObjekatIzvrsenjaOperacije();
            System.out.println("lista utakmica size: " + utakmicee.size());

            if (utakmicee.size() == 0) {
                throw new Exception("Ne postoje utakmice za izabrani datum");
            }

            pdf.Pdf.generisiPdfListu(utakmicee, vratiDatumSaNulom(jDateChooserPrviDatum.getDate()), vratiDatumKraj(jDateChooserDrugiDatum.getDate()), new Date());
            JOptionPane.showMessageDialog(this, "Uspesno ste generisali listu");

        } catch (IOException eio) {
            dispose();
            prikaziFormuPrijava();
        } catch (Exception ex) {
            ex.printStackTrace();

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_jButtonGnerisiListuActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("pdf/lista/lista.pdf");
                Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom otvaranja pdf fajla, probajte ponovo");
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        // TODO add your handling code here:
        jLabel3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseMoved
    private void prikaziFormuPrijava() {
        JOptionPane.showMessageDialog(this, "Izgubili ste konekciju sa serverom! Probajte ponovo da se ulogujete!");
        FPrijava fp = new FPrijava();
        fp.setLocationRelativeTo(null);
        fp.setResizable(false);
        fp.setVisible(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGnerisiListu;
    private javax.swing.JButton jButtonOtkazi;
    private com.toedter.calendar.JDateChooser jDateChooserDrugiDatum;
    private com.toedter.calendar.JDateChooser jDateChooserPrviDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
