/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import com.sun.javafx.scene.control.skin.VirtualFlow;
import domen.StavkaTiketa;
import domen.Tiket;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.scene.control.DatePicker;
import javax.swing.JOptionPane;
import komunikacija.KontrolerKI;
import transfer.ServerTransferObjekat;
import transfer.KlijentTransferObjekat;
import static forme.JPanelKreirajTiket.vratiDatumSaNulom;

/**
 *
 * @author KORISNIK
 */
public class JDialogStanje extends javax.swing.JDialog {

    /**
     * Creates new form JDialogStanje
     */
    public JDialogStanje(java.awt.Frame parent, boolean modal) throws ClassNotFoundException, IOException {
        super(parent, modal);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateChooserPrviDatum = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUkupnaUplata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUkupnaIsplata = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldStanje = new javax.swing.JTextField();
        jButtonStanje = new javax.swing.JButton();
        jDateChooserDrugiDatum = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPotencijalnaIsplata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPotencijalnoStanje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled stanja");

        jDateChooserPrviDatum.setDateFormatString("dd.MM.yyyy.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Izaberite od kog do kog datuma zelite stanje");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Ukupna uplata:");

        jTextFieldUkupnaUplata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUkupnaUplata.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldUkupnaUplata.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ukupna isplata:");

        jTextFieldUkupnaIsplata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUkupnaIsplata.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldUkupnaIsplata.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Trenutno stanje:");

        jTextFieldStanje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldStanje.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldStanje.setEnabled(false);

        jButtonStanje.setText("Stanje");
        jButtonStanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStanjeActionPerformed(evt);
            }
        });

        jDateChooserDrugiDatum.setDateFormatString("dd.MM.yyyy.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Potencijalna isplata:");

        jTextFieldPotencijalnaIsplata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPotencijalnaIsplata.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPotencijalnaIsplata.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Potencijalno stanje:");

        jTextFieldPotencijalnoStanje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPotencijalnoStanje.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPotencijalnoStanje.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUkupnaUplata, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jDateChooserPrviDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStanje)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldUkupnaIsplata, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPotencijalnoStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jTextFieldPotencijalnaIsplata))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateChooserDrugiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jDateChooserDrugiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonStanje)
                            .addComponent(jDateChooserPrviDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUkupnaUplata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUkupnaIsplata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPotencijalnaIsplata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPotencijalnoStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStanjeActionPerformed
        try {
            // TODO add your handling code here:
            if (jDateChooserPrviDatum.getDate() == null || jDateChooserDrugiDatum.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Morate izabrati oba datuma");
                return;
            }

            double ukupnaUplata = 0;
            double ukupnaIsplata = 0;
            double potencijalnaIsplata = 0;

            HashMap<String, Date> hmap = new HashMap<>();
            hmap.put("prviDatum", (vratiDatumSaNulom(jDateChooserPrviDatum.getDate())));
            hmap.put("drugiDatum", (JPanelKreirajTiket.vratiDatumKraj(jDateChooserDrugiDatum.getDate())));

            KlijentTransferObjekat zahtev12 = new KlijentTransferObjekat();
            zahtev12.setOperacija(KlijentTransferObjekat.VRATI_TIKETE);
            zahtev12.setObjekatOperacije(hmap);
            KontrolerKI.vratiInstancu().posaljiZahtev(zahtev12);
            ServerTransferObjekat odgovor12 = KontrolerKI.vratiInstancu().procitajOdgovor();
            if (odgovor12.getSignal() == -1) {
                throw new Exception(odgovor12.getPoruka());
            }
            List<Tiket> tiketi = (List<Tiket>) odgovor12.getObjekatIzvrsenjaOperacije();

            for (Tiket tiket : tiketi) {
                if (tiket.getVremeUplate() != null) {
                    ukupnaUplata += tiket.getUplata();
                    if (tiket.getStatus().equals("isplacen")) {
                        ukupnaIsplata += tiket.getDobitak();
                    }
                    if (tiket.getStatus().equals("aktivan")) {
                        potencijalnaIsplata += tiket.getDobitak();
                    }
                }
            }

            postaviPolja(ukupnaUplata, ukupnaIsplata, potencijalnaIsplata);
            JOptionPane.showMessageDialog(this, odgovor12.getPoruka());
        } catch (IOException ex) {
            this.dispose();
            prikaziFormuPrijava();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButtonStanjeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStanje;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooserDrugiDatum;
    private com.toedter.calendar.JDateChooser jDateChooserPrviDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldPotencijalnaIsplata;
    private javax.swing.JTextField jTextFieldPotencijalnoStanje;
    private javax.swing.JTextField jTextFieldStanje;
    private javax.swing.JTextField jTextFieldUkupnaIsplata;
    private javax.swing.JTextField jTextFieldUkupnaUplata;
    // End of variables declaration//GEN-END:variables

    private void postaviPolja(double ukupnaUplata, double ukupnaIsplata, double potencijalnaIsplata) {
        jTextFieldUkupnaUplata.setText(Double.toString((Math.round((ukupnaUplata) * 100.0) / 100.0)));
        jTextFieldUkupnaIsplata.setText(Double.toString((Math.round((ukupnaIsplata) * 100.0) / 100.0)));
        jTextFieldPotencijalnaIsplata.setText(Double.toString((Math.round((potencijalnaIsplata) * 100.0) / 100.0)));
        jTextFieldStanje.setText(Double.toString((Math.round((ukupnaUplata - ukupnaIsplata) * 100.0) / 100.0)));
        jTextFieldPotencijalnoStanje.setText(Double.toString((Math.round((ukupnaUplata - ukupnaIsplata - potencijalnaIsplata) * 100.0) / 100.0)));
    }

    private void prikaziFormuPrijava() {
        JOptionPane.showMessageDialog(this, "Izgubili ste konekciju sa serverom! Probajte ponovo da se ulogujete!");
        FPrijava fp = new FPrijava();
        fp.setLocationRelativeTo(null);
        fp.setResizable(false);
        fp.setVisible(true);
    }

}
