/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author KORISNIK
 */
public class JDialogKonfiguracijaServera extends javax.swing.JDialog {

    private File file;
    private OutputStream outputStream;
    private Properties configProperty;

    /**
     * Creates new form JDialogKonfiguracijaServera
     */
    public JDialogKonfiguracijaServera(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        postaviConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIPAdresa = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonPodesiParametre = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfiguracija servera");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("IP adresa servera:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Port servera:");

        jTextFieldIPAdresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldPort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonPodesiParametre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPodesiParametre.setText("Podesi parametre");
        jButtonPodesiParametre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPodesiParametreActionPerformed(evt);
            }
        });

        jButtonOtkazi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPodesiParametre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOtkazi, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIPAdresa)
                            .addComponent(jTextFieldPort, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIPAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPodesiParametre)
                    .addComponent(jButtonOtkazi))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonPodesiParametreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPodesiParametreActionPerformed
        // TODO add your handling code here:
        int odg = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da hocete da podesite parametre?");
        if (odg == 0) {
            try {
                String ipAdresa = jTextFieldIPAdresa.getText();
                int port = Integer.parseInt(jTextFieldPort.getText());

                file = new File("config.properties");
                configProperty.setProperty("ipAdresa", ipAdresa);
                configProperty.setProperty("port", Integer.toString(port));

                outputStream = new FileOutputStream(file);
                configProperty.store(outputStream, null);
                outputStream.close();
                JOptionPane.showMessageDialog(this, "Uspesno ste podesili parametre");
                dispose();
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Port mora biti broj!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Nisu uspesno podeseni parametri!");
            }
        }
    }//GEN-LAST:event_jButtonPodesiParametreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonPodesiParametre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldIPAdresa;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables

    private void postaviConfig() throws FileNotFoundException, IOException {

        configProperty = new Properties();

        configProperty.setProperty("ipAdresa", "localhost");
        configProperty.setProperty("port", "9000");

        jTextFieldIPAdresa.setText(configProperty.getProperty("ipAdresa"));
        jTextFieldPort.setText(configProperty.getProperty("port"));
    }
}
