/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Radnik;
import domen.Tip;
import domen.UplatnoMesto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.io.IOException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import komunikacija.KontrolerKI;
import repozitorijum.Repozitorijum;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author KORISNIK
 */
public class JPanelUnosRadnika extends javax.swing.JPanel {

    private Object buttonGroup;
    private boolean imeUspesno = false;
    private boolean prezimeUspesno = false;
    private boolean korImeUspesno = false;
    private boolean sifraUspesno = false;
    private boolean ponovljenaSifraUspesno = false;
    public static Thread nitProvereUnosRadnika;
    private boolean nitRadi = false;

    /**
     * Creates new form JPanelUnosRadnika
     */
    public JPanelUnosRadnika() {
        initComponents();
        pripremiPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonKreirajNovogRadnika = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonSacuvajRadnika = new javax.swing.JButton();
        jTextFieldIDRadnika = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBoxUplatnaMesta = new javax.swing.JComboBox<>();
        jRadioButtonRadnik = new javax.swing.JRadioButton();
        jRadioButtonAdministrator = new javax.swing.JRadioButton();
        jLabelSifraJeKratka = new javax.swing.JLabel();

        jButtonKreirajNovogRadnika.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonKreirajNovogRadnika.setText("Kreiraj novog radnika");
        jButtonKreirajNovogRadnika.setNextFocusableComponent(jTextFieldIme);
        jButtonKreirajNovogRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajNovogRadnikaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID radnika:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ime:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Prezime:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Korisnicko ime:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sifra:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ponovite sifru:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Uplatno mesto:");

        jButtonSacuvajRadnika.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSacuvajRadnika.setText("Sacuvaj radnika");
        jButtonSacuvajRadnika.setEnabled(false);
        jButtonSacuvajRadnika.setNextFocusableComponent(jButtonKreirajNovogRadnika);
        jButtonSacuvajRadnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajRadnikaActionPerformed(evt);
            }
        });

        jTextFieldIDRadnika.setEditable(false);
        jTextFieldIDRadnika.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldIDRadnika.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIDRadnika.setEnabled(false);

        jTextFieldIme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldIme.setNextFocusableComponent(jTextFieldPrezime);
        jTextFieldIme.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldImeCaretUpdate(evt);
            }
        });

        jTextFieldPrezime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPrezime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPrezime.setNextFocusableComponent(jTextFieldKorisnickoIme);
        jTextFieldPrezime.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldPrezimeCaretUpdate(evt);
            }
        });

        jTextFieldKorisnickoIme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldKorisnickoIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldKorisnickoIme.setNextFocusableComponent(jPasswordField1);
        jTextFieldKorisnickoIme.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldKorisnickoImeCaretUpdate(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField1.setNextFocusableComponent(jPasswordField2);
        jPasswordField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField1CaretUpdate(evt);
            }
        });

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField2.setNextFocusableComponent(jComboBoxUplatnaMesta);
        jPasswordField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField2CaretUpdate(evt);
            }
        });

        jComboBoxUplatnaMesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxUplatnaMesta.setNextFocusableComponent(jButtonSacuvajRadnika);

        jRadioButtonRadnik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonRadnik.setSelected(true);
        jRadioButtonRadnik.setText("Radnik");
        jRadioButtonRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRadnikActionPerformed(evt);
            }
        });

        jRadioButtonAdministrator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonAdministrator.setText("Administrator");

        jLabelSifraJeKratka.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSifraJeKratka.setText("sifra je kratka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxUplatnaMesta, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonRadnik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonAdministrator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelSifraJeKratka))
                            .addComponent(jTextFieldIDRadnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonKreirajNovogRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvajRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(513, 513, 513))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButtonKreirajNovogRadnika)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSifraJeKratka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonRadnik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAdministrator)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxUplatnaMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButtonSacuvajRadnika)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajRadnikaActionPerformed
        // TODO add your handling code here:
        nitRadi = false;
        Radnik r = new Radnik();
        r.setIdRadnika(Repozitorijum.noviRadnik.getIdRadnika());
        String status = "";
        if (jRadioButtonRadnik.isSelected()) {
            status = "radnik";
        } else {
            status = "administrator";
        }
        UplatnoMesto um = (UplatnoMesto) jComboBoxUplatnaMesta.getSelectedItem();
        r.setIme(jTextFieldIme.getText());
        r.setPrezime(jTextFieldPrezime.getText());
        r.setKorisnickoIme(jTextFieldKorisnickoIme.getText());
        r.setStatus(status);
        r.setUplatnoMesto(um);
        r.setSifraRadnika(jPasswordField1.getText());

        try {
            sacuvajRadnika(r);

        } catch (IOException eio) {
            prikaziFormuPrijava();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButtonSacuvajRadnikaActionPerformed

    private void jButtonKreirajNovogRadnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajNovogRadnikaActionPerformed
        // TODO add your handling code here:
        try {

            Radnik radnik = new Radnik();
            UplatnoMesto um = new UplatnoMesto();
            um.setIdUplatnogMesta(1);
            radnik.setUplatnoMesto(um);
            KlijentTransferObjekat zahtev = new KlijentTransferObjekat();
            zahtev.setOperacija(KlijentTransferObjekat.KREIRAJ_NOVOG_RADNIKA);
            zahtev.setObjekatOperacije(radnik);
            KontrolerKI.vratiInstancu().posaljiZahtev(zahtev);
            ServerTransferObjekat odgovor = KontrolerKI.vratiInstancu().procitajOdgovor();

            if (odgovor.getSignal() == -1) {
                throw new Exception(odgovor.getPoruka());
            }
            Repozitorijum.noviRadnik = (Radnik) odgovor.getObjekatIzvrsenjaOperacije();

        } catch (IOException eio) {
            prikaziFormuPrijava();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }

        resetujPolja();
        postaviIDRadnika();
    }//GEN-LAST:event_jButtonKreirajNovogRadnikaActionPerformed

    private void jRadioButtonRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRadnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRadnikActionPerformed

    private void jTextFieldImeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldImeCaretUpdate
        // TODO add your handling code here:

        String ime = jTextFieldIme.getText();
        if (ime.length() == 0) {
            jTextFieldIme.setBorder(BorderFactory.createLineBorder(Color.red));
            imeUspesno = false;
        } else {
            jTextFieldIme.setBorder(BorderFactory.createLineBorder(Color.green));
            imeUspesno = true;
        }
    }//GEN-LAST:event_jTextFieldImeCaretUpdate

    private void jTextFieldPrezimeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldPrezimeCaretUpdate
        // TODO add your handling code here:
        String prezime = jTextFieldPrezime.getText();
        if (prezime.length() == 0) {
            jTextFieldPrezime.setBorder(BorderFactory.createLineBorder(Color.red));
            prezimeUspesno = false;
        } else {
            jTextFieldPrezime.setBorder(BorderFactory.createLineBorder(Color.green));
            prezimeUspesno = true;
        }
    }//GEN-LAST:event_jTextFieldPrezimeCaretUpdate

    private void jTextFieldKorisnickoImeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldKorisnickoImeCaretUpdate
        // TODO add your handling code here: String prezime= jTextFieldPrezime.getText();
        String korIme = jTextFieldKorisnickoIme.getText();
        if (korIme.length() == 0) {
            jTextFieldKorisnickoIme.setBorder(BorderFactory.createLineBorder(Color.red));
            korImeUspesno = false;
        } else {
            jTextFieldKorisnickoIme.setBorder(BorderFactory.createLineBorder(Color.green));
            korImeUspesno = true;
        }
    }//GEN-LAST:event_jTextFieldKorisnickoImeCaretUpdate

    private void jPasswordField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField1CaretUpdate
        // TODO add your handling code here:
        String sifra = jPasswordField1.getText();
        if (sifra.length() < 8) {
            jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.red));
            jLabelSifraJeKratka.setVisible(true);
            sifraUspesno = false;
        } else {
            jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.green));
            jLabelSifraJeKratka.setVisible(false);
            sifraUspesno = true;
        }
    }//GEN-LAST:event_jPasswordField1CaretUpdate

    private void jPasswordField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField2CaretUpdate
        // TODO add your handling code here:
        String ponovljenaSifra = jPasswordField2.getText();
        String sifra = jPasswordField1.getText();
        if (!sifra.equals(ponovljenaSifra) || ponovljenaSifra.length() == 0) {
            jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.red));
            ponovljenaSifraUspesno = false;
        } else {
            jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.green));
            ponovljenaSifraUspesno = true;
        }
    }//GEN-LAST:event_jPasswordField2CaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonKreirajNovogRadnika;
    private javax.swing.JButton jButtonSacuvajRadnika;
    private javax.swing.JComboBox<Object> jComboBoxUplatnaMesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSifraJeKratka;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButtonAdministrator;
    private javax.swing.JRadioButton jRadioButtonRadnik;
    private javax.swing.JTextField jTextFieldIDRadnika;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void dodajRadioGroup() {
        buttonGroup1.add(jRadioButtonRadnik);
        buttonGroup1.add(jRadioButtonAdministrator);
    }

    private void popuniCBUplatnihMesta() throws IOException, ClassNotFoundException, Exception {
        jComboBoxUplatnaMesta.removeAllItems();
        KlijentTransferObjekat zahtev = new KlijentTransferObjekat();
        zahtev.setOperacija(KlijentTransferObjekat.VRATI_SVA_UPLATNA_MESTA);
        KontrolerKI.vratiInstancu().posaljiZahtev(zahtev);
        ServerTransferObjekat odgovor = KontrolerKI.vratiInstancu().procitajOdgovor();
        if (odgovor.getSignal() == -1) {
            throw new Exception(odgovor.getPoruka());
        }
        List<UplatnoMesto> uplatnaMesta = (List<UplatnoMesto>) odgovor.getObjekatIzvrsenjaOperacije();

        for (UplatnoMesto um : uplatnaMesta) {
            jComboBoxUplatnaMesta.addItem(um);
        }
    }

    private void prikaziFormuPrijava() {
        JOptionPane.showMessageDialog(this, "Izgubili ste konekciju sa serverom! Probajte ponovo da se ulogujete!");
        FPrijava fp = new FPrijava();
        fp.setLocationRelativeTo(null);
        fp.setResizable(false);
        fp.setVisible(true);
    }

    private void postaviIDRadnika() {
        jTextFieldIDRadnika.setText(Integer.toString(repozitorijum.Repozitorijum.noviRadnik.getIdRadnika()));
    }

    private void resetujPolja() {
        jTextFieldIDRadnika.setText("");
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jTextFieldKorisnickoIme.setText("");

        jTextFieldIDRadnika.setBorder(BorderFactory.createLineBorder(Color.black));
        jTextFieldIme.setBorder(BorderFactory.createLineBorder(Color.black));
        jTextFieldPrezime.setBorder(BorderFactory.createLineBorder(Color.black));
        jTextFieldKorisnickoIme.setBorder(BorderFactory.createLineBorder(Color.black));

        jPasswordField1.setText("");
        jPasswordField2.setText("");

        jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.black));
        jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.black));

        jRadioButtonRadnik.setSelected(true);
    }

    private void pripremiPanel() {
        nitRadi = true;
        jLabelSifraJeKratka.setVisible(false);
        dodajRadioGroup();
        try {
            popuniCBUplatnihMesta();
        } catch (IOException ex) {
            prikaziFormuPrijava();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        postaviIDRadnika();
        pokreniNitZaProveru();
    }

    private void pokreniNitZaProveru() {

        nitProvereUnosRadnika = new Thread(new Runnable() {
            @Override
            public void run() {
                while (!nitProvereUnosRadnika.isInterrupted()) {
                    if (imeUspesno == true && prezimeUspesno == true && korImeUspesno == true && sifraUspesno == true && ponovljenaSifraUspesno == true) {
                        jButtonSacuvajRadnika.setEnabled(true);
                    } else {
                        jButtonSacuvajRadnika.setEnabled(false);
                    }
                }
            }
        });
        nitProvereUnosRadnika.start();
    }

    private void sacuvajRadnika(Radnik r) throws IOException, Exception {
        KlijentTransferObjekat zahtev4 = new KlijentTransferObjekat();
        zahtev4.setOperacija(KlijentTransferObjekat.SACUVAJ_RADNIKA);
        zahtev4.setObjekatOperacije(r);
        KontrolerKI.vratiInstancu().posaljiZahtev(zahtev4);
        ServerTransferObjekat odgovor4 = KontrolerKI.vratiInstancu().procitajOdgovor();
        if (odgovor4.getSignal() == -1) {
            throw new Exception(odgovor4.getPoruka());
        }

        JOptionPane.showMessageDialog(null, odgovor4.getPoruka());
    }
}
